//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDroid.ColorPickers
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int color_picker_view = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int new_color_panel = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int old_color_panel = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_color_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int color1_summary = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int color1_title = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int color2_summary = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int color2_title = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int color3_summary = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int color3_title = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int color4_summary = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int color4_title = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int dialog_color_picker = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int pref_category = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int press_color_to_apply = 2130968578;
			
			private String()
			{
			}
		}
	}
}
