//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDroid.ColorPickers
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ButtonColorAlpha = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int ButtonColorNoAlpha = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ButtonRoundColor = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int PanelColorAlpha = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int PanelColorNoAlpha = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int PanelRoundColor = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int color_picker_view = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int new_color_panel = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int old_color_panel = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_color_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int button_color_picker_alpha = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int button_color_picker_noalpha = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int button_color_picker_round = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int dialog_color_picker = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int press_color_to_apply = 2130968578;
			
			private String()
			{
			}
		}
	}
}
