#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cheesebaron.ColorPickersSample.Resource", IsApplication=true)]

namespace Cheesebaron.ColorPickersSample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cheesebaron.ColorPickers.Resource.Id.color_picker_view = global::Cheesebaron.ColorPickersSample.Resource.Id.color_picker_view;
			global::Cheesebaron.ColorPickers.Resource.Id.new_color_panel = global::Cheesebaron.ColorPickersSample.Resource.Id.new_color_panel;
			global::Cheesebaron.ColorPickers.Resource.Id.old_color_panel = global::Cheesebaron.ColorPickersSample.Resource.Id.old_color_panel;
			global::Cheesebaron.ColorPickers.Resource.Layout.dialog_color_picker = global::Cheesebaron.ColorPickersSample.Resource.Layout.dialog_color_picker;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int ButtonColorAlpha = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ButtonColorNoAlpha = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ButtonRoundColor = 2130837506;
			
			// aapt resource value: 0x7F020006
			public const int color_picker_view = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int new_color_panel = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int old_color_panel = 2130837512;
			
			// aapt resource value: 0x7F020003
			public const int PanelColorAlpha = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int PanelColorNoAlpha = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int PanelRoundColor = 2130837509;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int dialog_color_picker = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int button_color_picker_alpha = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int button_color_picker_noalpha = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int button_color_picker_round = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int dialog_color_picker = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int press_color_to_apply = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
